name: Python CI for day5/演習3

on:
  push:
    branches: [ master ] # またはリポジトリのデフォルトブランチ名
    paths:
      - 'day5/演習3/**'
      - 'day5/requirements.txt'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ master ] # またはリポジトリのデフォルトブランチ名
    paths:
      - 'day5/演習3/**'
      - 'day5/requirements.txt'
      - '.github/workflows/ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./day5 # ワーキングディレクトリを day5 に設定

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # requirements.txt や環境に合わせたバージョンを指定

    - name: Install dependencies
      run: |
        python -m venv ../.venv_ci # day5 の一つ上の階層に仮想環境を作成
        source ../.venv_ci/bin/activate
        pip install -r requirements.txt

    - name: Cache performance metrics
      uses: actions/cache@v4
      with:
        path: 演習3/models/.performance_metrics.json
        key: ${{ runner.os }}-pip-${{ hashFiles('演習3/models/.performance_metrics.json') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Run tests with pytest
      run: |
        source ../.venv_ci/bin/activate
        pytest 演習3/tests

    - name: Archive performance metrics if tests passed
      if: success() # テストが成功した場合のみ実行
      uses: actions/upload-artifact@v4
      with:
        name: performance-metrics
        path: 演習3/models/.performance_metrics.json 